name: katalog
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets :
    - assets/JurassicW.jpg
    - assets/background.jpg
    - assets/itsprofil.jpg
    - assets/cover.jpg
    - assets/WaIcon.jpg
    - assets/InstaIg.jpg
    - assets/tele.jpg
    - assets/Emaillogo.jpg